name: Send Day Weather Update

on:
  schedule:
    # 12:00 Poland time = 11:00 UTC
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  day_weather:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install requests

      - run: python day_weather.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          LAT: ${{ secrets.LAT }}
          LON: ${{ secrets.LON }}
