name: Save Night Weather

on:
  schedule:
    # 01:01 Poland time (CET/CEST) â†’ 00:01 UTC
    - cron: '1 00 * * *'
  workflow_dispatch:

jobs:
  night_weather:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # allows using GITHUB_TOKEN to push

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install requests

      - run: python night_weather.py
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          LAT: ${{ secrets.LAT }}
          LON: ${{ secrets.LON }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
